#!/bin/sh

### BEGIN INIT INFO
# Provides:                     jira
# Required-Start:               $local_fs $remote_fs $network exim postgresql apache2
# Should-Start:                 
# Should-Stop:                  
# Required-Stop:                $local_fs $remote_fs $network exim postgresql apache2
# Default-Start:                3 5
# Default-Stop:                 0 1 2 6
# Short-Description:            JIRA Tomcat Server
# Description:                 	Start the JIRA Tomcat Server
### END INIT INFO

# JIRA Linux service controller script
cd "/srv/jira/bin/bin"

. /etc/rc.status
rc_reset

case "$1" in
    start)
	echo -n "Starting up Jira"
	
	./start-jira.sh

	/usr/sbin/rcapache2 restart

	rc_status -v
	;;
    stop)
	echo -n "Shuting down Jira"

	./stop-jira.sh

	rc_status -v
	;;
    restart)
	$0 stop
	$0 start
	rc_status
	;;
    status)
	echo -n "Checking for service Jira: "
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac
rc_exit

